// frontend-vue/src/modules/form/components/Formulario.vue
<template>
  <div class="card shadow">
    <div class="card-header bg-primary text-white">
      <h4 class="mb-0">📝 Registro de Formulario</h4>
    </div>
    <div class="card-body">
      <form @submit.prevent="handleSubmit">
        <!-- DNI -->
        <div class="mb-3">
          <label class="form-label fw-bold">DNI/Cédula *</label>
          <input
              class="form-control"
              :class="{ 'is-invalid': errors.dni }"
              placeholder="Ingrese DNI"
              v-model="form.dni"
              :disabled="isSubmitting"
          />
          <div v-if="errors.dni" class="invalid-feedback">
            {{ errors.dni }}
          </div>
        </div>

        <!-- Nombres -->
        <div class="mb-3">
          <label class="form-label fw-bold">Nombres *</label>
          <input
              class="form-control"
              :class="{ 'is-invalid': errors.nombres }"
              placeholder="Ingrese nombres"
              v-model="form.nombres"
              :disabled="isSubmitting"
          />
          <div v-if="errors.nombres" class="invalid-feedback">
            {{ errors.nombres }}
          </div>
        </div>

        <!-- Apellidos -->
        <div class="mb-3">
          <label class="form-label fw-bold">Apellidos *</label>
          <input
              class="form-control"
              :class="{ 'is-invalid': errors.apellidos }"
              placeholder="Ingrese apellidos"
              v-model="form.apellidos"
              :disabled="isSubmitting"
          />
          <div v-if="errors.apellidos" class="invalid-feedback">
            {{ errors.apellidos }}
          </div>
        </div>

        <!-- Fecha de Nacimiento -->
        <div class="mb-3">
          <label class="form-label fw-bold">Fecha de Nacimiento *</label>
          <input
              type="date"
              class="form-control"
              :class="{ 'is-invalid': errors.fechaNacimiento }"
              v-model="form.fechaNacimiento"
              :disabled="isSubmitting"
              :max="today"
          />
          <div v-if="errors.fechaNacimiento" class="invalid-feedback">
            {{ errors.fechaNacimiento }}
          </div>
        </div>

        <!-- Género -->
        <div class="mb-3">
          <label class="form-label fw-bold d-block">Género *</label>
          <div class="form-check form-check-inline">
            <input
                class="form-check-input"
                type="radio"
                id="generoM"
                value="M"
                v-model="form.genero"
                :disabled="isSubmitting"
            />
            <label class="form-check-label" for="generoM">
              Masculino
            </label>
          </div>
          <div class="form-check form-check-inline">
            <input
                class="form-check-input"
                type="radio"
                id="generoF"
                value="F"
                v-model="form.genero"
                :disabled="isSubmitting"
            />
            <label class="form-check-label" for="generoF">
              Femenino
            </label>
          </div>
          <div v-if="errors.genero" class="text-danger small">
            {{ errors.genero }}
          </div>
        </div>

        <!-- Ciudad -->
        <div class="mb-3">
          <label class="form-label fw-bold">Ciudad *</label>
          <select
              class="form-select"
              :class="{ 'is-invalid': errors.ciudad }"
              v-model="form.ciudad"
              :disabled="isSubmitting"
          >
            <option value="">Seleccione Ciudad</option>
            <option value="Quito">Quito</option>
            <option value="Guayaquil">Guayaquil</option>
            <option value="Cuenca">Cuenca</option>
            <option value="Milagro">Milagro</option>
            <option value="Manta">Manta</option>
            <option value="Ambato">Ambato</option>
          </select>
          <div v-if="errors.ciudad" class="invalid-feedback">
            {{ errors.ciudad }}
          </div>
        </div>

        <!-- Error de envío -->
        <div v-if="errors.submit" class="alert alert-danger" role="alert">
          {{ errors.submit }}
        </div>

        <!-- Botón -->
        <button
            type="submit"
            class="btn btn-primary w-100"
            :disabled="isSubmitting"
        >
          <span v-if="isSubmitting">
            <span class="spinner-border spinner-border-sm me-2"></span>
            Guardando...
          </span>
          <span v-else>💾 Guardar Formulario</span>
        </button>
      </form>
    </div>
  </div>
</template>

<script>
import {computed} from "vue";
import {useForm} from "../composables/useForm";
import formService from "../services/formService";

export default {
  name: "Formulario",
  emits: ["formSaved"],
  setup(props, {emit}) {
    const initialFormState = {
      dni: "",
      nombres: "",
      apellidos: "",
      fechaNacimiento: "",
      genero: "",
      ciudad: "",
    };

    const {form, errors, isSubmitting, validate, resetForm, setSubmitting} =
        useForm(initialFormState);

    const today = computed(() => {
      return new Date().toISOString().split("T")[0];
    });

    const handleSubmit = async () => {
      if (!validate()) {
        return;
      }

      setSubmitting(true);

      try {
        await formService.insert(form.value);
        alert("✅ Formulario guardado exitosamente!");
        resetForm();
        emit("formSaved");
      } catch (error) {
        alert(`❌ Error: ${error.message}`);
        errors.value.submit = error.message;
      } finally {
        setSubmitting(false);
      }
    };

    return {
      form,
      errors,
      isSubmitting,
      today,
      handleSubmit,
    };
  },
};
</script>

// frontend-react/src/modules/form/components/Formulario.jsx
import React from "react";
import {saveForm} from "../services/formService";
import {useForm} from "../hooks/useForm";

const initialFormState = {
    dni: "",
    nombres: "",
    apellidos: "",
    fechaNacimiento: "",
    genero: "",
    ciudad: "",
};

export function Formulario({onFormSaved}) {
    const {
        form,
        errors,
        isSubmitting,
        handleChange,
        validate,
        resetForm,
        setIsSubmitting,
        setErrors
    } = useForm(initialFormState);

    const handleSubmit = async (e) => {
        e.preventDefault();

        // Validar formulario
        if (!validate()) {
            return;
        }

        setIsSubmitting(true);

        try {
            await saveForm(form);
            alert("✅ Formulario guardado exitosamente!");
            resetForm();

            // Notificar al componente padre para recargar la lista
            if (onFormSaved) {
                onFormSaved();
            }
        } catch (error) {
            alert(`❌ Error: ${error.message}`);
            setErrors({submit: error.message});
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div className="card shadow">
            <div className="card-header bg-primary text-white">
                <h4 className="mb-0">📝 Registro de Formulario</h4>
            </div>
            <div className="card-body">
                <form onSubmit={handleSubmit}>
                    <div className="mb-3">
                        <label className="form-label fw-bold">DNI/Cédula *</label>
                        <input
                            className={`form-control ${errors.dni ? "is-invalid" : ""}`}
                            placeholder="Ingrese DNI"
                            name="dni"
                            value={form.dni}
                            onChange={handleChange}
                            disabled={isSubmitting}
                        />
                        {errors.dni && (
                            <div className="invalid-feedback">{errors.dni}</div>
                        )}
                    </div>

                    <div className="mb-3">
                        <label className="form-label fw-bold">Nombres *</label>
                        <input
                            className={`form-control ${errors.nombres ? "is-invalid" : ""}`}
                            placeholder="Ingrese nombres"
                            name="nombres"
                            value={form.nombres}
                            onChange={handleChange}
                            disabled={isSubmitting}
                        />
                        {errors.nombres && (
                            <div className="invalid-feedback">{errors.nombres}</div>
                        )}
                    </div>

                    <div className="mb-3">
                        <label className="form-label fw-bold">Apellidos *</label>
                        <input
                            className={`form-control ${errors.apellidos ? "is-invalid" : ""}`}
                            placeholder="Ingrese apellidos"
                            name="apellidos"
                            value={form.apellidos}
                            onChange={handleChange}
                            disabled={isSubmitting}
                        />
                        {errors.apellidos && (
                            <div className="invalid-feedback">{errors.apellidos}</div>
                        )}
                    </div>

                    <div className="mb-3">
                        <label className="form-label fw-bold">Fecha de Nacimiento *</label>
                        <input
                            type="date"
                            className={`form-control ${errors.fechaNacimiento ? "is-invalid" : ""}`}
                            name="fechaNacimiento"
                            value={form.fechaNacimiento}
                            onChange={handleChange}
                            disabled={isSubmitting}
                            max={new Date().toISOString().split('T')[0]}
                        />
                        {errors.fechaNacimiento && (
                            <div className="invalid-feedback">{errors.fechaNacimiento}</div>
                        )}
                    </div>

                    <div className="mb-3">
                        <label className="form-label fw-bold d-block">Género *</label>
                        <div className="form-check form-check-inline">
                            <input
                                className="form-check-input"
                                type="radio"
                                name="genero"
                                id="generoM"
                                value="M"
                                checked={form.genero === "M"}
                                onChange={handleChange}
                                disabled={isSubmitting}
                            />
                            <label className="form-check-label" htmlFor="generoM">
                                Masculino
                            </label>
                        </div>
                        <div className="form-check form-check-inline">
                            <input
                                className="form-check-input"
                                type="radio"
                                name="genero"
                                id="generoF"
                                value="F"
                                checked={form.genero === "F"}
                                onChange={handleChange}
                                disabled={isSubmitting}
                            />
                            <label className="form-check-label" htmlFor="generoF">
                                Femenino
                            </label>
                        </div>
                        {errors.genero && (
                            <div className="text-danger small">{errors.genero}</div>
                        )}
                    </div>

                    <div className="mb-3">
                        <label className="form-label fw-bold">Ciudad *</label>
                        <select
                            name="ciudad"
                            className={`form-select ${errors.ciudad ? "is-invalid" : ""}`}
                            value={form.ciudad}
                            onChange={handleChange}
                            disabled={isSubmitting}
                        >
                            <option value="">Seleccione Ciudad</option>
                            <option value="Quito">Quito</option>
                            <option value="Guayaquil">Guayaquil</option>
                            <option value="Cuenca">Cuenca</option>
                            <option value="Milagro">Milagro</option>
                            <option value="Manta">Manta</option>
                            <option value="Ambato">Ambato</option>
                        </select>
                        {errors.ciudad && (
                            <div className="invalid-feedback">{errors.ciudad}</div>
                        )}
                    </div>

                    {errors.submit && (
                        <div className="alert alert-danger" role="alert">
                            {errors.submit}
                        </div>
                    )}

                    <button
                        type="submit"
                        className="btn btn-primary w-100"
                        disabled={isSubmitting}
                    >
                        {isSubmitting ? (
                            <>
                                <span className="spinner-border spinner-border-sm me-2"></span>
                                Guardando...
                            </>
                        ) : (
                            "💾 Guardar Formulario"
                        )}
                    </button>
                </form>
            </div>
        </div>
    );
}
